# Use NVIDIA CUDA as base image and run the same installation as in the other packages.
# The version of cudatoolkit must match those of the base image, see Dockerfile.pytorch
FROM nvidia/cuda:11.0-cudnn8-runtime-ubuntu18.04
RUN chmod 1777 /tmp && chmod 1777 /var/tmp
